# Generated by Django 3.1.1 on 2020-09-25 06:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w .@+-_]+$', 'Enter a valid name. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='Item Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.image_upload_path, verbose_name='Item Image')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=15, verbose_name='Satus')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('special', models.BooleanField(default=False, verbose_name='Special')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w .@+-_]+$', 'Enter a valid name. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='Categorie Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.image_upload_path, verbose_name='Categories Image')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=15, verbose_name='Satus')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
            ],
            options={
                'verbose_name': 'Menu Categorie',
                'verbose_name_plural': 'Menu Categories',
                'db_table': 'menu_categorie',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w .@+-_]+$', 'Enter a valid name. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='Order Number')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Order Date')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Bill Amount')),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=15, verbose_name='Payment Satus')),
                ('order_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Acknowledged', 'Acknowledged'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=15, verbose_name='Prder Satus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w .@+-_]+$', 'Enter a valid name. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='Table Number')),
                ('seating', models.PositiveIntegerField(null=True, verbose_name='Seating Capicity')),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.image_upload_path, verbose_name='Categories Image')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Vacent', 'Vacent')], default='Active', max_length=15, verbose_name='Satus')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.PositiveIntegerField(null=True, verbose_name='Item Qty')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='restaurant.items', verbose_name='Item')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='restaurant.orders', verbose_name='Order Number')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='restaurant.tables', verbose_name='Table Number')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='MenuSubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w .@+-_]+$', 'Enter a valid name. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='Categorie Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.image_upload_path, verbose_name='Categories Image')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=15, verbose_name='Satus')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
                ('cateory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='restaurant.menucategories', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Sub Categorie',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'sub_categorie',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='sub_cateory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.menusubcategories', verbose_name='Sub Categorie'),
        ),
    ]
