# Generated by Django 3.1.1 on 2020-09-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='table_number',
        ),
        migrations.AddField(
            model_name='orders',
            name='table_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.tables', verbose_name='Table Number'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Bill Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Acknowledged', 'Acknowledged'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=15, verbose_name='Order Satus'),
        ),
    ]
