# Generated by Django 3.1.1 on 2020-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200925_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Bill Amount'),
        ),
    ]
