# Generated by Django 3.1.1 on 2020-09-29 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20200925_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Coupon Code')),
                ('description', models.TextField(default=None)),
                ('discount_type', models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], default='Flat', max_length=15, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Value')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_till', models.DateField(verbose_name='Valid Till')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=15, verbose_name='Satus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tables',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Vacent', 'Vacent')], default='Vacent', max_length=15, verbose_name='Satus'),
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.coupon', verbose_name='Coupon Code'),
        ),
    ]
